plugins {
    alias(budgetplus.plugins.android.app)
    alias(budgetplus.plugins.metro)
    alias(budgetplus.plugins.compose)
    alias(libs.plugins.androidx.baselineprofile)
}

// Consume the Baseline Profile generated by the :benchmark module and merge it into
// src/main so every release variant (including the published one) ships it. See
// https://developer.android.com/topic/performance/baselineprofiles/configure-baselineprofiles
baselineProfile {
    // Write the generated profile into src/main/generated/baselineProfiles so it is
    // picked up by all release builds, replacing the previously hand-committed
    // src/main/baseline-prof.txt.
    mergeIntoMain = true
    // Regenerate on every run rather than relying on a stored artifact.
    saveInSrc = true
}

dependencies {
    implementation(enforcedPlatform(libs.firebase.bom))
    implementation(libs.firebase.analytics)
    implementation(libs.firebase.crashlytics)

    implementation(libs.kermit)
    implementation(libs.profile.installer)

    implementation(projects.shared)

    baselineProfile(projects.benchmark)
}
